use_frameworks!

platform :ios, '8.0'

target 'ShaheTool_Example' do
  pod 'ShaheTool', :path => '../'

  target 'ShaheTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
